# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a4f7441dec6dd3e9dce59e7f915e06bed7cb8dc190de4d3195b6c63f2f4a7725ed86e48e2a21e142217e77a7f1a98f8ead61a7ada341885fcb5fdb46cb6bb4e

test:
  secret_key_base: 33e5ed84457e8ec065fb6d0bd91573ad52826185e5477bcdcf4de5f5e90dd8b7093c83267ea04156cc6954c42bfd0bff0d1d0c93316fb40e0a5dbba4dc632ffb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
